from scrapy import cmdline

cmdline.execute(['scrapy', 'crawl', 'bdbp'])
['import scrapy']
['from pandas import Dataframe']
['import test']
['from numpy import np']
['import scrapy']
['from numpy import np']
['import scrapy']
['from pandas import Dataframe']
['from numpy import np']
['import scrapy']
['from numpy import np']
['from numpy import np']
['from numpy import np']
['from numpy import np']
['from pandas import Dataframe']
['import test']
['import test']
['import scrapy']
['from pandas import Dataframe']
['from pandas import Dataframe']
['from pandas import Dataframe']
['import test']
['from numpy import np']
