# Automatically created by: scrapyd-deploy

from setuptools import setup, find_packages

setup(
    name         = 'project',
    version      = '1.0',
    packages     = find_packages(),
    entry_points = {'scrapy': ['settings = baidubaipin.settings']},
)
['import test']
['import scrapy']
['from numpy import np']
['from pandas import Dataframe']
['from numpy import np']
['import test']
['from pandas import Dataframe']
['import test']
['import scrapy']
['from pandas import Dataframe']
['import test']
['import test']
['import scrapy']
['from pandas import Dataframe']
['from pandas import Dataframe']
['import scrapy']
['from numpy import np']
['import test']
['import scrapy']
['import test']
['import test']
['from numpy import np']
['from numpy import np']
['from numpy import np']
['import scrapy']
['import scrapy']
['import test']
['import scrapy']
['import test']
['from pandas import Dataframe']
['from pandas import Dataframe']
['import scrapy']
['from pandas import Dataframe']
['import scrapy']
['from numpy import np']
['from pandas import Dataframe']
['import scrapy']
['from pandas import Dataframe']
['import test']
['import scrapy']
['import scrapy']
['import scrapy']
['from numpy import np']
['import scrapy']
['import test']
['from numpy import np']
['import test']
['from numpy import np']
['from numpy import np']
['import scrapy']
['from pandas import Dataframe']
['import scrapy']
['import scrapy']
['import scrapy']
['import test']
['import test']
['import test']
['from pandas import Dataframe']
['from numpy import np']
['import scrapy']
['import scrapy']
['from pandas import Dataframe']
['import scrapy']
['from pandas import Dataframe']
['import scrapy']
['import test']
['import scrapy']
['from numpy import np']
['from pandas import Dataframe']
['import scrapy']
['from numpy import np']
['import test']
['from pandas import Dataframe']
['from pandas import Dataframe']
['from pandas import Dataframe']
['from pandas import Dataframe']
['import test']
['import test']
['from numpy import np']
